name: build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ðŸ›  Run the build script
        shell: pwsh
        run: ./buildMaster.ps1; ./buildManifests.ps1
      - name: ðŸŒŠ Commit the new 'compiled' build
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Autobuild
#     - name: ðŸŒŠ Upload new build to Releases
#       uses: marvinpinto/action-automatic-releases@latest
#       with:
#         repo_token: ${{ secrets.GITHUB_TOKEN }}
#         automatic_release_tag: nightly
#         prerelease: false
#         title: TweakList AutoBuild
#         files: Master.ps1
